policies:
  - name: Local Updatecli Policies
    config:
      - updatecli/updatecli.d
    values:
      - updatecli/values.d/scm.yaml
  - name: Handle Updatecli Policy Updates
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.10.0@sha256:588fb5b274c1e484198885723b5a67688416feeec414d41a33908826e448fd41
    values:
      - updatecli/values.d/scm.yaml
  - name: Handle NPM
    policy: ghcr.io/updatecli/policies/autodiscovery/npm:0.13.0@sha256:83beffb8b5a12f2c36226d19063abcc45112416309effb8a57968bf2a04564e4
    values:
      - updatecli/values.d/scm.yaml
  - name: Update githubactions
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.3.0@sha256:3b5425da2a2a2b89bb69463f1294704c33730358c66140efb93cab14b2868b06
    values:
      - updatecli/values.d/scm.yaml
