policies:
  - name: Local Updatecli Policies
    config:
      - updatecli/updatecli.d
    values:
      - updatecli/values.d/scm.yaml
  - name: Handle Updatecli Policy Updates
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.8.0@sha256:99e9e61b501575c2c176c39f2275998d198b590a3f6b1fe829f7315f8d457e7f
    values:
      - updatecli/values.d/scm.yaml
  - name: Handle NPM
    policy: ghcr.io/updatecli/policies/autodiscovery/npm:0.11.0@sha256:f5df5357738270ed51804ad175d892a86b34b08482086a25189a9b23a456ccf0
    values:
      - updatecli/values.d/scm.yaml
