policies:
  - name: Local Updatecli Policies
    config:
      - updatecli/updatecli.d
    values:
      - updatecli/values.d/scm.yaml
  - name: Handle Updatecli Policy Updates
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.10.0@sha256:588fb5b274c1e484198885723b5a67688416feeec414d41a33908826e448fd41
    values:
      - updatecli/values.d/scm.yaml
  - name: Handle NPM
    policy: ghcr.io/updatecli/policies/autodiscovery/npm:0.11.0@sha256:f5df5357738270ed51804ad175d892a86b34b08482086a25189a9b23a456ccf0
    values:
      - updatecli/values.d/scm.yaml
  - name: Update githubactions
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.1.0@sha256:ddac4fc192800a65e9a92669600db3eb66fe442610073d34202513b265ba7b29
    values:
      - updatecli/values.d/scm.yaml
