name: Release Drafter
on:
  workflow_dispatch:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - v1
jobs:
  update_release_draft:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@c345907820e0396f6f44bcfd9ac4763325f8feb0 # v7.8.0
        with:
          config-name: release-drafter.yaml
          publish: startsWith(github.ref, "refs/tags")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
